DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetSdkVersion, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetColorMode, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetDensityDpi, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, float, GetFontScale, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetFontWeightAdjustment, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetHardKeyboardHidden, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetKeyboard, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetKeyboardHidden, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetMcc, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetMnc, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetNavigation, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetNavigationHidden, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetOrientation, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetScreenHeightDp, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetScreenLayout, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetScreenWidthDp, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetSmallestScreenWidthDp, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetTouchscreen, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, int, GetUIMode, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, const char*, GetLocaleLanguage, () const, ())
DECLARE_INSTANCE_METHOD(UnityConfiguration, const char*, GetLocaleCountry, () const, ())


